version: '3.9'
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product-service
    ports:
      - '6000:6000'
    volumes:
      - pgdata1:/var/lib/postgresql/data

  api:
    container_name: api_backend
    build: .
    volumes:
      - .:/app
    environment:
      DB_SCHEMA: product-service
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    depends_on:
      - db
    ports:
      - '3000:3000'

volumes:
  pgdata1: {}
